version: "3.8"

services:
  pgsql.my:
    image: pgsql
    volumes:
      - pgsql_socket:/var/run/postgresql/
      - pgsql_data:/var/lib/postgresql/data
      - php_fpm_socket:/run/php-fpm/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pgsql424258541

  php-fpm.my:
    image: mphp8-fpm
    volumes:
      - ./web_server_config/php/php.ini:/usr/local/etc/php/php.ini
      - ./web_server_config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./web_server_config/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./www/index.php:/var/www/html/index.php
      - pgsql_socket:/var/run/postgresql/
      - php_fpm_socket:/run/php-fpm/
      - ./vendor:/var/www/vendor
      - ./src:/var/www/src
      - ./composer.json:/var/www/composer.json
      - ./composer.phar:/var/www/composer.phar
      - ./composer.lock:/var/www/composer.lock

  nginx:
    image: nginx:alpine
    volumes:
      - ./web_server_config/nginx/static_error_pages:/usr/share/nginx/html
      - ./web_server_config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web_server_config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/index.php:/var/www/html/index.php
      - ./assets/:/var/www/html/assets/
      - php_fpm_socket:/run/php-fpm/
    ports:
      - "8080:80"

volumes:
  pgsql_data:
  pgsql_socket:
  php_fpm_socket:
